### ISSUE TITLE
New selectionaction-type Multipoint

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-selection-actions#12]
Informationen:
- Mindestens für Selection-Methode "point" wäre ein "multiselect"-Mode sehr praktisch, d.h. wenn
dieser aktiv ist, werden die Selections für die aktiven Layer im Resultcenter "appended" statt
"replaced"
- z.B. konfigurierbar über selectionOptions {"point":{multiselect":true|false}}
- Noch schöner: multiselect bei gleichzeitig gedrückter [STRG]-Taste aktiv
- Prinzipiell wäre "multiselect"-Mode auf bei den Selection-Modi "rectangle" und "polygon" eine
brauchbare Erweiterung, für "point"-Selection aber richtig gut.

**Comment by sholtkamp** [comment]
Added in version 1.11.0
