### ISSUE TITLE
Dynamic step size for circle selection action

### ISSUE THREAD

**Issue by martinlohoff** [conterra/mapapps-selection-actions#13]
Hi Matthias,

uns ist beim Nutzen der Umkreissuche ein nice-to-have in den Sinn gekommen. Meist ist es ja so, dass man bei kleineren Umkreisen etwas feiner den Radius (Bsp.: 555m) definieren und bei grösseren nur grob einen Radius (Bsp.: 250.000m) angeben möchte. Via Konfiguration lässt sich das aktuell nur bedingt lösen. Den stepSize kann man nur global für alle Grössen definieren.

Könnte man das dynamischer machen?

Freundliche Grüsse
Martin

**Comment by sholtkamp** [comment]
Added in #18
