### ISSUE TITLE
Queries with time awareness

### ISSUE THREAD

**Issue by martinlohoff** [conterra/mapapps-selection-actions#15]
Hi @matthiasstein . Bzgl. der Query Tools (geometrisch und attributiv) habe ich ein Anliegen. Aus meiner Sicht sollten die Queries auch zeitliche Einschränkungen unterstützen, wenn die Layer Zeit unterstützen. Mit dem TimeSlider hattet ihr ja schon eingebaut, dass man bei Start der App einen TimeExtent definieren kann. Dieser und jeweils der, der mit dem Slider gesetzt wird, sollte dann auch bei den Queries aus den bekannten Tools berücksichtigt werden.

Grüsse
Martin

**Comment by matthiasstein** [comment]
Innerhalb vom LayerStore wird die zeitliche Einschränkung bedacht, wenn der Layer auch über einen timeExtent verfügt. Dies funktioniert allerdings nur für FeatureLayer. Bei Sublayern von MapImageLayern funktioniert dies nicht, da diese über gar keine timeExtent-Property verfügen.
Bisher hat der TimeSlider den timeExtent nur auf die view angewandt. Mit dem neuen Release https://github.com/conterra/mapapps-time-slider/releases/tag/6.3.0 nun aber auch auf jeden in der Karte enthaltenen Layer.
