### ISSUE TITLE
Obscure log in console when using area (Gebiet) selection action

### ISSUE THREAD

**Issue by antoniave** [conterra/mapapps-selection-actions#16]
If the user performs a selection using the area (Gebiet) selection action, a log (simple log, no error or warning) from FeatureLayer is shown in the console: 
![image](https://user-images.githubusercontent.com/11754039/192724613-5f13ef97-8079-4dde-8e36-e00cfc41c404.png)

**Comment by matthiasstein** [comment]
This is a problem in the demo, because there are two layers loaded that do not have a geometry field. I will adjust the demo.
